import type { Metadata } from "next";
import { Geist, Geist_Mono, Caladea, Source_Code_Pro, Fira_Sans, Eczar, Source_Sans_3, Quicksand } from "next/font/google";
import "./globals.css";


// const quickSand = Quicksand({
//   weight: ["300", "500", "600","700"],
//   variable: "--font-quick-sand",
//   subsets: ["latin"],
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased h-screen w-screen font-quicksand`}
      >
        {children}
      </body>
    </html>
  );
}
