# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      my_secret: ${{secrets.commit_secret}}
      
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://ftadev.github.io

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build 
    - run: npm test
    - run: |
          cd out
          git init
          # type configurations: your user.email and user.name followed lines
          # git config --global user.email your_email
          # git config --global user.name your_name
          git config --global user.email akhlaghi.fatemeh@gmail.com
          git config --global user.name ftadev
          git status
          # change this remote url for examle your remote url is https://github.com/FtADev/ftadev.github.io.git then the following:
          git remote add origin https://${{secrets.commit_secret}}@github.com/FtADev/ftadev.github.io.git
          # git checkout -b gh-pages
          # echo "ftadev.ir" > CNAME
          git add --all
          git commit -m "update"
          git push origin master -f
